build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards-related webhooks APIs"
  contactDetails:
    name: "Sandra Harald - Product Owner 2025"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2385
    - (936) 564-0000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
