server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enable: true
  info:
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
  instance:
    prefer-ip-address: true

# Connect with the discovery server/eureka server and locate all the details of individual microservices
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
