server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enable: true
  info:
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
  instance:
    prefer-ip-address: true

# Connect with the discovery server/eureka server and locate all the details of individual microservices
spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              # disabled default routing configurations/behaviour
              enabled: false
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 20s


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

info:
  app:
    description: "Easy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

# Circuit breaker pattern configuration
resilience4j.circuitbreaker:
  configs:
    default:
      # This defines the number of calls in the sliding window that will be used to calculate the failure rate.
      # In this case, it's 10, so the CircuitBreaker will track the last 10 calls.
      # These calls can be successful or failed, and their outcome determines whether to open the circuit.
      slidingWindowSize: 5
      # This sets the time the circuit will stay open before transitioning to half-open, in milliseconds.
      # Here, 10000 milliseconds = 10 seconds.
      # After this time, the circuit will attempt trial calls as specified by
      waitDurationInOpenState: 10s
      # This defines how many trial calls are allowed when the circuit breaker is in a half-open state.
      # Here, 2 means that when transitioning from open to half-open, it will allow 2 calls.
      # If those calls succeed, the circuit goes to closed; if they fail, it goes back to open.
      permittedNumberOfCallsInHalfOpenState: 2
      # This sets the failure rate threshold as a percentage.
      # If more than 50% of the calls in the sliding window fail, the circuit will open.
      # For example, if 6 out of the last 10 calls fail, the failure rate is 60%, which is above the threshold.
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10s # Important: this is your circuit breaker's internal timeout