build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related web hook APIs to test monitor api"
  contactDetails:
    name: "Pelias Sudhir - Product Owners"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
