
spring:
  cloud:
    consul:
      host: ${CONSUL_SERVER_ADDRESS:localhost}
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    openfeign:
      okhttp:
        enabled: true
  config:
    import: "configserver:http://localhost:8071/"

  profiles:
    active: test
  application:
    name: rempms-candidate-service